### ISSUE TITLE
Implement optional field dependencies

### ISSUE THREAD

**Issue by tschneidereit** [tschneidereit/SwiftSuspenders#1]
Right now, SwiftSuspenders throws errors for each injection point no binding is found for.
Extending the metadata would allow making injection points optional:
[Inject(required="false")]

Parsley does this:
http://www.spicefactory.org/parsley/docs/2.0/manual/injection.php#property_type

**Comment by tschneidereit** [comment]
I'm not sure this is even desirable, so I'll postpone it for now.

**Comment by tschneidereit** [comment]
Decided against it: optional dependencies are best dealt with using optional arguments to ctors or injected methods.

**Comment by Glidias** [comment]
Yes, but if you do have a lot of fields, than it can mean a lot of boiler plate on the class' part. However, in such a case, i tend to use another package like Camo/F*CSS's PropertyApplier/IApplicator  to apply such properties instead, where you don't need to litter a class with so many meta tags.

**Comment by tschneidereit** [comment]
It seems to me like if you've got a lot of optional public variables/ setters on your class, it's highly unlikely that they're all going to be satisfiable by an injector anyway.

A solution such as a CSS implementation where you can specify a complex identifier for resolving these dependencies (i.e., a CSS selector) seems to me to make much more sense.
