### ISSUE TITLE
PropertyInjection fails poorly

### ISSUE THREAD

**Issue by squeedee** [tschneidereit/SwiftSuspenders#10]
In a class some place i have:       

[Inject(name="IncompleteIntervalsService")]
public var intervalService:IIntervalService;

But I don't have a mapping declared (because of a typographic error, yay magic strings in meta)

injector.mapSingletonOf(IIntervalService, IncompleteIntervalService, "IncompleteIntervalService");

(missing an 's')

Causes an unhandled RTE. I think it should raise an exception in PropertyInjectionPoint.as line 37 (where mappings is null)

**Comment by tschneidereit** [comment]
That sounds like a bug indeed. Thanks for the heads-up, will investigate.

**Comment by tschneidereit** [comment]
Bugfix in handling unsatisfied named injection requests. Includes unit test coverage.

Closed by f2588e3fc1c59c361c28ec059c925a3995d991ff
