### ISSUE TITLE
The second parameter type of SwiftSuspendersInjector::mapClass

### ISSUE THREAD

**Issue by imcotton** [tschneidereit/SwiftSuspenders#12]
I saw this code at README.textile
<code>var currentTime : Date = new Date();
injector.mapClass(Date, currentTime, 'currentTime');</code>

Isn't the second parameter request _Class_ type? Why there full with a instance? Doesn't the compiler throw a Compile-Time error?

**Comment by tschneidereit** [comment]
Fixed an error in the documentation.

Closed by fb13cee3b2f99bb87c8fa82f19133163297abbfe
