### ISSUE TITLE
injector.mapValue -- XML?

### ISSUE THREAD

**Issue by shovemedia** [tschneidereit/SwiftSuspenders#16]
For some reason I can't inject XML? The constructor property is returning XMLList?
Am I a moron? All my other datatypes inject just fine...

**Comment by shovemedia** [comment]
I think the XML class behaves the same as Proxy? Changing line 122:
            if (target is Proxy || target is XML)
no more problems?

**Comment by tschneidereit** [comment]
Thanks for the report - and thanks shovemedia for the suggested fix, which I think to very likely be correct.
I'll verify and apply the fix in the next release.

**Comment by tschneidereit** [comment]
FIX: Injector throws exception when trying to inject into mapped XML values

Closed by b3ffebbd71408591261decc9d0b7be52444b70d1
