### ISSUE TITLE
Trouble with mapValue values that evaluate to false

### ISSUE THREAD

**Issue by shovemedia** [tschneidereit/SwiftSuspenders#17]
If the value i'm trying to map is Boolean = false or String "" the injection appears to fail.
(didn't try Number = zero yet)

I tried changing !injectionPoint checks to injectionPoint == null, but I couldn't fix it and it's 3am : )

Thoughts?

**Comment by tschneidereit** [comment]
Thanks for the report - I'll check and fix it ASAP

**Comment by tschneidereit** [comment]
FIX: Trouble with mapValue values that evaluate to false.

Closed by 870ab56a24119ab56c0104e7b74e8cb5a2cf7763

**Comment by shovemedia** [comment]
I was initially trying to use mapSingletonOf -- does the fix address other mappings besides mapValue?

and thanks!

**Comment by tschneidereit** [comment]
The fix should address all mapping types, as the problem was with a piece of code that doesn't even know about different mapping types.

I'll roll a new release with fixes for this and ticket #16 in a few minutes.

**Comment by texastoland** [comment]
Till did you test this?  I believe you require strict equality.  "anything == null" should evaluate to true given:  null, false, empty String, 0, NaN, and undefined (but not in this case since only wildcards can have this value).  Try "injector === null":

http://www.adobe.com/livedocs/flash/9.0/ActionScriptLangRefV3/operators.html#strict_equality

**Comment by tschneidereit** [comment]
Yes, I added a unit test for it. All of the values you mention are "falsy", i.e. "!value" evaluates to true if "value" contains one of them.
That doesn't mean that they evaluate to null, though. Only null and undefined yield true if compared to null.

Thanks for the comment, though - it's always good to double-check stuff like this.

**Comment by texastoland** [comment]
Thx I learned something new :)

**Comment by shovemedia** [comment]
Incidentally, in the particular context I wrote, I did, in fact, need to wrap my boolean in an object in order for it to behave as desired -- ie the same boolean is injected multiple places and if changed once, is changed everywhere. All primitives would require something similar.
