### ISSUE TITLE
child injectors should share the map of worked injectees from their parent

### ISSUE THREAD

**Issue by tschneidereit** [tschneidereit/SwiftSuspenders#18]
Right now, a value that's shared between injectors and mapped with more than one rule will get injection applied to them for each of the involved injectors.

To resolve this, all injectors should share a map of worked injectees.

**Comment by artemb** [comment]
Hi! Any thoughts on when this can be resolved?

**Comment by tschneidereit** [comment]
Changed child injectors to reuse their parent's map of worked injectees

Closed by 2f4c482eaf3a863891c3d8b4d23a0785f4d5e01e
