### ISSUE TITLE
Injecting a previously injected instance

### ISSUE THREAD

**Issue by kristoferjoseph** [tschneidereit/SwiftSuspenders#20]
This might be more of a use case than a bug. 
I have a bootstrap loader app with it's own context that prepares a service class by injecting all of it's dependencies. 
I then load a sub-app with it's own context and wanted to use injector.mapValue(IMyInterface, myInstance) to inject it around the sub application. This fails because the injector tries to inject the dependencies that have already been injected by the bootstrap into the instance supplied. This seems to be working exactly as intended. Which makes sense. I would like a flag to be able to tell the injector that the injections have already been supplied to the instance and to just map the value. 

I have gotten around this by just using the instance passed from the boot strap loader in a service locator style approach; No injections, but this changes the way I test it. 

Ideas?

**Comment by tschneidereit** [comment]
Thanks for the explanation. That's an issue that Shaun and others have already brought up. By now, I think it really is a bug - specifically, the fact that the injector ever tries injects into an object that mapped with mapValue is a bug.
As much as I'm willing to fix this problem, I fear that it might cause subtle, very hard to debug changes in runtime behavior for some people.

I'll once again bring this to the attention of the Robotlegs list, in the hope of people agreeing that the change is ok and can be implemented in a point release.

**Comment by tschneidereit** [comment]
Changed behavior of mapValue: Mapped values aren't injected into once they are themselves injected into another instance anymore

Closed by c051fe970d1e15f129bfa91c48a3bed6e66ccae1

**Comment by kristoferjoseph** [comment]
Great news. Thanks for the fix. I will roll it in immediately.
