### ISSUE TITLE
Add support for injection into non-public namespaces

### ISSUE THREAD

**Issue by dwabyick** [tschneidereit/SwiftSuspenders#23]
It would be great to configure swift_suspenders to inject into non-public namespaces.  The use-case for this is through Robotlegs with MVCS entities.    This doesn't have severe implications, as often I'm programming to interfaces, but it still seems like semantically, the objects are often implementation details.

**Comment by tschneidereit** [comment]
The problem is that the Flex compiler only stored metadata for public fields of a class. That means that even though it is possible to get at fields in a custom namespace (not at ones that are private or protected, though), there's no way to find out which of them should be injected into.

**Comment by dwabyick** [comment]
I see. Would be nice to have metadata for custom namespaces. Perhaps I'll put in a request.

**Comment by tschneidereit** [comment]
I think the new Flex compiler that is supposed to be released in a few months should have a metadata or at least a bytecode processor built into its compilation steps, so that will hopefully make more advanced annotations possible.
