### ISSUE TITLE
[FUG] getInstance throws an error when no rule is found

### ISSUE THREAD

**Issue by joelhooks** [tschneidereit/SwiftSuspenders#24]
http://github.com/tschneidereit/SwiftSuspenders/blob/master/src/org/swiftsuspenders/Injector.as#L163

expected result:
when I getInstance and there is no rule for it, I should get back null.

actual result:
NOE

why:
I want to use an object if it has a rule, but if not I want to create the rule.

options:
hasMappingForClass(Class) or hasRule(forClass) or return null

I don't want to have to try/catch every time!

**Comment by joelhooks** [comment]
http://github.com/tschneidereit/SwiftSuspenders/blob/master/src/org/swiftsuspenders/Injector.as#L148

doh! IInjector needs this.

**Comment by tschneidereit** [comment]
Oh right: We totally forgot about adding that to Robotlegs' IInjector! Will do so!

**Comment by joelhooks** [comment]
I still **really** think that getInstance should not throw an error, but instead provide an instance of the class via Injector#instantiate. The API suggests to me that I am going to get an instance, not an error. Otherwise it should be getMappedInstance to let me know that is a very specific call.
