### ISSUE TITLE
proposal for new map method in Injector

### ISSUE THREAD

**Issue by nodename** [tschneidereit/SwiftSuspenders#26]
http://knowledge.robotlegs.org/discussions/questions/148-customizing-injection

if Injector had a mapFactory() method, then I could say

injector.mapFactory(SomeServiceClass, myFactoryMethod);

...

private function myFactoryMethod(serviceClass:Class):AbstractService
{
var service:AbstractService = new serviceClass();
serviceRepresentative.addServicePendingListener(service);
return service;
}

**Comment by darscan** [comment]
Howdy,

Any thoughts on mapFactory? I see that Mr Nodename weaved an impl. Have you had a chance to check it out? I'm quite interested in this idea.. opens up a great many possibilities..

**Comment by darscan** [comment]
Also, I see that you proposed this very thing yourself a while back:

http://github.com/tschneidereit/SwiftSuspenders/issues#issue/21

**Comment by hvilela** [comment]
I would like to see this feature too. I've missed it already.

**Comment by tschneidereit** [comment]
In Swiftsuspenders 2, this will be possible with `injector.map(type).toProvider(myCustomProvider);`, where `myCustomProvider` has to implement the interface `DependencyProvider`, which consists of one method `apply(targetType:Class, usingInjector:Injector) : Object`.
