### ISSUE TITLE
Confused about singleton in parent injector

### ISSUE THREAD

**Issue by jmboone** [tschneidereit/SwiftSuspenders#28]
Hi,

I hope this is the correct place to ask the question.  I want to define a singleton object with my shell parent injector mapping (e.g. SessionModel), and then inject the SAME singleton instance into my modules which are children injectors of the shell injector.  The injection mapping is indeed happening in the children but it is not the same instance as the parent like I had expected. Is this just a misunderstanding of how parent/child injectors work or perhaps a bug?  Thanks!

Jim

**Comment by tschneidereit** [comment]
Sorry for the extremely late reply. I'm sure you're long done with your project, so this is just to thank you for the bug report. I'll take a look and fix it in a future release.
