### ISSUE TITLE
Add meaningful trace to createDummyInstance error handling

### ISSUE THREAD

**Issue by Reider** [tschneidereit/SwiftSuspenders#30]
Please add some more trace info in ConstructorInjectionPoint::createDummyInstance. 
Currently there is only a trace(error); so when I ran into a null pointer error because of the dummy instance creation flash player bugfix I had to spend a lot time to track down where the error trace was coming from.

Instead of:
catch (error : Error)
{
    trace(error);
}

Use something like:

catch (error : Error)
{
    trace("Error when creating dummy instance of class " ,clazz, error);
}

Or don't write anything. This could save someone a lot of trouble.

**Comment by tschneidereit** [comment]
Add meaningful trace to createDummyInstance error handling

Closed by f30555d1aa592f7ea7d4aa94798fb95f305d554c
