### ISSUE TITLE
injector.unInjectTo()

### ISSUE THREAD

**Issue by kyoji2** [tschneidereit/SwiftSuspenders#34]
If I inject something to a loaded content(in a child application domain), it will be impossible to unload that content from memory. Because the loaded content itself and it's class definition is saved in there dictionaries inside the Injector instance.
So I suggest an unInjectTo(target:Object) method. It's important to dynamically loading modules.

public function unInjectInto(target : Object) : void
        {
            if (m_attendedToInjectees[target])
            {
                delete m_attendedToInjectees[target];
            }

```
        var ctor : Class = getConstructor(target);

        if (m_injectionPointLists[ctor])
        {
            delete m_injectionPointLists[ctor];

            var description : XML = describeType(ctor);
            delete m_injectionPointLists[description.@name.toString()];
        }

        if(m_constructorInjectionPoints[ctor])
        {
            delete m_constructorInjectionPoints[ctor];
        }
    }
```

**Comment by vizio360** [comment]
Hi kyoji2,

I've got a fork for this purpose 

https://github.com/vizio360/SwiftSuspenders

the fork is based on an old version of swiftsuspenders. 
I've added a removeInjectionReferencesOf(target : Object) function to be able to unload externally loaded swf files.

Btw I think Till is going to release a new version where he will address this issue.

**Comment by tschneidereit** [comment]
As @vizio360 says, the Injector doesn't store information about which instances it injected into anymore in version 2. Additionally, there will be an explicit way to tear down objects, causing their [PreDestroy]-annotated methods to be called. But that'll not really be required for this use-case.
