### ISSUE TITLE
Nonrequired injections proposal

### ISSUE THREAD

**Issue by hvilela** [tschneidereit/SwiftSuspenders#35]
When the injection is missing sometimes is preferable to receive a null value than an Exception.
For this cases I would like to have an option like this:

[Inject (optional=true)] public var someService:SomeService;

**Comment by tschneidereit** [comment]
SwiftSuspenders-35: Enabled optional injections for methods

Including unit tests. Additionally, the commit contains some small cleanup in property naming and other aspects of the source code

Closed by ac09a536276a21b22355cf930bf16632710c513a
