### ISSUE TITLE
Attempting to instantiate() an interface should throw an informative error

### ISSUE THREAD

**Issue by robertpenner** [tschneidereit/SwiftSuspenders#37]
I made the mistake of trying to call injector.instantiate(IThing) instead of on Thing.
The error message from Flash Player wasn't obvious at first:

VerifyError: Error #1001: The method asunit.framework::IRunnerFactory() is not implemented.

It would be nice if SwiftSuspenders could detect the interface and throw an informative error.

**Comment by tschneidereit** [comment]
Added meaningful exception for attempts at treating interfaces as instantiatable

Closed by 42d961247fd095255cf413ed6fd651765e50c5b4
