### ISSUE TITLE
Creation of classes and their injection in Child Injectors

### ISSUE THREAD

**Issue by neilmanuell** [tschneidereit/SwiftSuspenders#40]
been playing with child injectors... at the moment if a mapping is not overridden in the child injector the parent injector creates AND injects the instance. This means that any injections within the requested class are those mapped in the parent, even if  those rules are overridden in the requesting child.

It would be cool if you could choose which injector actually injects the class. Obviously this brings up a whole load of issues (ie those mapped as Singletons should always be as is.

**Comment by tschneidereit** [comment]
What you describe shouldn't happen with child injectors. In fact, I worked quite hard to make sure that SwiftSuspenders returns to using the child injector after fetching a dependency from the parent injector. And that applies to dependencies of the parent mapping, too.
If you haven't, yet, I recommend reading my blog post about child injectors:
http://www.tillschneidereit.de/2010/05/15/swiftsuspenders-1-5-or-a-tale-of-robots-and-refactorings/
It's rather lengthy and I apologize for that, but I hope it helps in fully getting to know SwiftSuspenders' child injectors.
Also, here's the unit test that verifies that the child injector keeps being used after a request has been forwarded to the parent:
https://github.com/tschneidereit/SwiftSuspenders/blob/master/test/org/swiftsuspenders/ChildInjectorTests.as#L95

**Comment by neilmanuell** [comment]
Ahh, I see that I was injecting my class in the parent as a Singleton (doh) works now I have changed to mapClass :)

cheers

**Comment by neilmanuell** [comment]
BTW enjoying using child injectors a lot, looking forward to live injections ;~)

**Comment by tschneidereit** [comment]
Glad it's working for you!

And I'd be very interested in any feedback you might have: Child injectors are the most complex part if SwiftSuspenders by far, so I'm sure there are a few rough corners that could use some sanding here and there.
