### ISSUE TITLE
Why m_injectionPointLists and m_constructorInjectionPoints are not weakref Dictionaries?

### ISSUE THREAD

**Issue by vizio360** [tschneidereit/SwiftSuspenders#42]
Hi Till,

I don't know if this is the right place to post this question but I was curious to know if there is a reason on why **m_injectionPointLists** and **m_constructorInjectionPoints** are not weakref Dictionaries.

I've got a Modular Robotlegs application which loads external swf files which are robolges modules. It looks like I cannot unload them properly. I've run the app through the profiler in FDT4 and after doing a `unloadAndStop(true)`, the current instance number for the module doesn't decrease.

So I made **m_injectionPointLists** and **m_constructorInjectionPoints** weakref Dictionaries and I now can unload the modules properly. At least I see the instance number going down.
Problem is that I don't know if that change could break something else. I already run your unit test and everything seems ok.

thanks
Simone

**Comment by tschneidereit** [comment]
Hi Simone,

you're completely right: They should be weakref'd. In fact, I have a new version of SwiftSuspenders nearly ready contains some refactorings in this area, one of which is to combine these two dictionaries into one `m_injecteeDescriptions` dictionary, which is weakrefed. If you're using child injectors, you might also be happy to hear that another major change is that injection points are now cached across mediators, eliminating the overhead of gathering them anew for all child injectors.

**Comment by vizio360** [comment]
Hi Till,

thanks for the quick response! :) nice to hear that a new version is on its way.

btw I did mention the same problem a year ago :) and forked your repo
here it is
https://github.com/vizio360/SwiftSuspenders

I did add a new function to get rid of all the references for a specific object
<code>
public function removeInjectionReferencesOf(target : Object):void
</code>

but I got ignored :( 

just joking!

Simone

**Comment by vizio360** [comment]
Hi till,

just a clarification of my bad joke above (hope you didn't get it wrong :) ) you didn't ignore me you gave me pretty extensive responses 

Simone

**Comment by tschneidereit** [comment]
Hi Simone,

no worries: I got the joke _and_ I really did slack when it came to integrating other people's forks. I hope to change that soon, as I just described (in the last paragraph) of my [latest blog post](http://www.tillschneidereit.de/2011/02/05/swiftsuspenders-1-6-a-tale-of-small-changes-and-big-plans/).

cheers,
till

**Comment by vizio360** [comment]
Hi Till,

no worries I'm the same :) , really looking forward for version 2!

btw are you on twitter?

Simone

**Comment by tschneidereit** [comment]
Yes: [@tschneidereit](http://twitter.com/tschneidereit)
