### ISSUE TITLE
Restrict access to mappings for child injectors

### ISSUE THREAD

**Issue by vizio360** [tschneidereit/SwiftSuspenders#45]
Is there a way to restrict access to some mappings for child injectors?

so to have some private mappings in the parent injectors which are not accessible by its children?

This came up because right now we are facing that situation.

We have some singletons which should stay private in the context of the main application but some other which should be available for the children. 

Could it be a good idea to add this functionality?

**Comment by tschneidereit** [comment]
Mmh, that's an interesting idea. Some sort of access control mechanism would be required. Although, in the simplest implementation, that would probably boil down to a "don't propagate to child injectors"-flag.

I'll think about it some more and see if it can be implemented efficiently.

**Comment by neilmanuell** [comment]
I had a similar thought.
I am using Child Injectors for Modular development. It would be good to be able to suppress injections of actors that should only be accessible to (for example ) the shell.

**Comment by tschneidereit** [comment]
This is supported using map(type).local() in Swiftsupenders 2.
