### ISSUE TITLE
Add support for optional parameters to method and constructor injection

### ISSUE THREAD

**Issue by tschneidereit** [tschneidereit/SwiftSuspenders#5]

**Comment by darscan** [comment]
+1. Just got bit by this! Is it hard to implement?

**Comment by tschneidereit** [comment]
Shouldn't be too hard - will look at it later today.

**Comment by robertpenner** [comment]
I was bit by this as well.

**Comment by tschneidereit** [comment]
I've got a nearly working solution for this - shouldn't be too long now. And I'll definitely include it in 1.0.

**Comment by tschneidereit** [comment]
Added support for optional parameters to method and constructor injections

Tests for the new functionality have been added as well.
Closed by 44dee47412c9c4e080284ace126694992d228220
