### ISSUE TITLE
Suggestions for hooks in 2.0

### ISSUE THREAD

**Issue by squeedee** [tschneidereit/SwiftSuspenders#55]
Hey Till,

As you know i've been writing an map/injection hook system for 'Boiler' which just extends Injector. A couple of things I cam across you may find useful: 
- There are two types of before/after scenarios: (a) injection and (b) mapping. I find that further distinction when 'adding' handlers is pointless. Eg: injector.addMappingHandler(HandlerClassOrInstance), and several interfaces - IBeforMapHandler IAfterMapHandler etc.. You can see what i mean here:  https://github.com/squeedee/Boiler/blob/master/HookableSuspenders/src/main/hookableSuspenders/MappingHandlerCollection.as#L26
- Hooking into 'before injection' and 'after injection' isn't easy, because I normally want to get my own injections in the handlers (I've seen a lot of stack dumps lately)
- A more useful form of before/after injection handler would be one applied to a specific mapping... eg getMappping(BlahClass).addInjectionHandler(this). This would often be called from afterMappingHandlers.

Perhaps you know all this, and probably you'll disagree, but I thought I'd cast some opinions. Happy to chat on Skype if you need me to make more sense than i did here :D

**Comment by squeedee** [comment]
Oh and clearly my code is still missing a Before/After UnmapHandler.

**Comment by tschneidereit** [comment]
Swiftsuspenders now has hooks that cover all of these scenarios
