### ISSUE TITLE
Error when injecting named ArrayCollection

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#6]
Try: injector.mapValue(ArrayCollection, ac, "somename");

[Inject(name="somename")]
public var ac:ArrayCollection;

**Comment by tschneidereit** [comment]
Wow, that's unbelievably fucked up. Turns out that you just can't call object.constructor on classes inheriting from flash.utils.Proxy. time for yet another workaround ...

**Comment by tschneidereit** [comment]
Ok, found and implemented a fix with bearable overhead

**Comment by darscan** [comment]
Legend!

**Comment by texastoland** [comment]
Reflector#getClass needs this fix too.  Refatored yours to an internal package level method available to both and also implemented ApplicationDomain:

https://gist.github.com/a3322dc3e3cc697d6fbe
