### ISSUE TITLE
getMapping throws error (2.0.0b1)

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#60]
How can one query for the existence of a mapping? Calling getMapping() throws and error if no mapping is found. I would expect it to return null, or for a method called hasMapping() to be exposed.

**Comment by tschneidereit** [comment]
Mmh, I might have to work on my API, then. The injector has the
methods `satisfies` and `satisfiesDirectly`, the first of which most
likely is what you want to use, whereas the second most likely is what
you'd expect to be using.

The thing is that `hasMapping` wouldn't live up to its name if it
returned true if the injector itself _or one of its ancestors_ has a
mapping, but that's what you want to know 99% of the time.

Got any good naming suggestions?

**Comment by darscan** [comment]
Ah! I didn't see satisfies(). That'll work for me.

**Comment by tschneidereit** [comment]
Cool. But do you think that I should use a better name for that functionality?

**Comment by darscan** [comment]
Nope, I like it.

**Comment by tschneidereit** [comment]
Alright then, documentation it is. Thanks.
