### ISSUE TITLE
Metadata.xml

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#63]
The metadata.xml file used by IDEs to validate custom metadata is currently bundled into Robotlegs. When using Swiftsuspenders without Robotlegs there is no IDE completion/validation. This is wrong, the file should be moved into Swiftsuspenders and compiled into the SWC.

https://github.com/robotlegs/robotlegs-framework/blob/version2/src/metadata.xml

**Comment by darscan** [comment]
Ah, and you'll need something like this in the buildfile:

https://github.com/robotlegs/robotlegs-framework/blob/version2/build.xml#L70

**Comment by tschneidereit** [comment]
Absolutely right. Plus, with Swiftsuspenders 2 there will be some more
tags and parameters, so I'll add an updated version of the file to
Swiftsuspenders.

**Comment by tschneidereit** [comment]
The latest push and packaged SWC and ZIP files contain a (hopefully correct) metadata.xml

**Comment by darscan** [comment]
Awesome, works perfectly.

**Comment by tschneidereit** [comment]
Cool! Wish IntelliJ supported that yet.
