### ISSUE TITLE
Reflector

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#65]
Just some observations.

There is a Reflector, but getConstructor() sits outside and is a package level function. Why is that?

Also, getClass() accepts an ApplicationDomain but doesn't use it. Surely getConstructor should also accept an ApplicationDown and use it if passed?

**Comment by tschneidereit** [comment]
Good point about `getConstructor`. I've just removed that function and folded it into `Reflector#getClass`.

Also, I've removed the `ApplicationDomain` argument from `getClass`. As I removed support for using FQCNs as the first argument earlier, it's not needed anymore.

Thanks for the comments!
