### ISSUE TITLE
Building the SWC

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#67]
How are you building the SWC at the moment? Buildr or ant?

**Comment by tschneidereit** [comment]
Ant. Never got around to really looking into Buildr, to be honest.

**Comment by darscan** [comment]
Right. There are a couple of things making `ant` explode for me:

build.xml(15): That line was commented out - which results in `/Development/Projects/SwiftSuspenders/${FLEX_HOME}/frameworks is not a valid directory`

build.xml: The two lines which specify the player version cause issues for me - `<arg value="-target-player=10.2"/>`

InjectionMapping.as(10) - the wildcard import results in `Error: Definition org.swiftsuspenders could not be found.`

If I change those 4 things I can successfully build.

**Comment by darscan** [comment]
I can send a pull request with those changes, but I have a feeling that the first three are there for a reason.

**Comment by tschneidereit** [comment]
The first problem is simply a result of my using IntelliJ for
building. I have the FLEX_HOME env variable set there so I don't need
to set it in the loathsome .properties file. I probably shouldn't do
this, so a pull request is much appreciated.

As for the other problems: The \* import is something IntelliJ
annoyingly does sometimes. But why would it cause compiler errors? It
doesn't for me, at least.

And why does the `target-player` definition cause problems for you?
I'm using SDK 4.5, which one are you using?

**Comment by darscan** [comment]
Cool, will re-introduce the `user.properties` and `user.properties.eg` files and include them in the build.

Yeh, it's crazy weird. I've decided that wildcard imports are the devil. They manage to break automated refactoring in both Eclipse _and_ IntelliJ. I think this problem only arises with `ant package`, but not sure why.

I'm using the 4.6 SDK. Will try 4.5

**Comment by tschneidereit** [comment]
Great, thanks!

I _despise_ wildcard imports, really. With a proper IDE, you don't save any time with them at all. And without one, you know even less about what's going on in your code.

**Comment by tschneidereit** [comment]
Fixed by merging @darscan's pull request
