### ISSUE TITLE
ApplicationDomain::getDefinition Explodes Fantastically

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#70]
Haven't had a chance to dig in properly yet, but after switching RL2 to the latest Swiftsuspenders we get a bunch of these: 

```
ReferenceError: Error #1065: Variable InjectedMediator is not defined.
    at flash.system::ApplicationDomain/getDefinition()
```

I've pushed an updated branch to:

https://github.com/darscan/robotlegs-framework/tree/swiftsuspeners-update

Run the tests to see what I'm on about.

**Comment by tschneidereit** [comment]
Indeed it did explode quite beautifully. It doesn't, now.
