### ISSUE TITLE
Can we get versioned SWC files in the download section?

### ISSUE THREAD

**Issue by joelhooks** [tschneidereit/SwiftSuspenders#8]
Since SwiftSuspenders SWC got taken out of the Robotlegs Framework swc/project, I need a way to link to a SWC for people not inclined to download the whole repo.

**Comment by tschneidereit** [comment]
Yeah, I'm planning to do that once I'm a little bit less swamped with work in the next few days.

**Comment by tschneidereit** [comment]
Finally done after Joel was kind enough to implement proper build  and release scripts.
