### ISSUE TITLE
InstantiateUnmapped Performance

### ISSUE THREAD

**Issue by darscan** [tschneidereit/SwiftSuspenders#86]
Just a reminder about checking out possible performance problems with `instantiateUnmapped()`

**Comment by tschneidereit** [comment]
I looked into this and can't find any reason why this should be slow. Additionally, it is used internally by the instance and singleton providers, so at least the former should be slow, too.

Can you give me a hint for reducing a good test-case so I can do some further digging?

**Comment by darscan** [comment]
Yeh, forget this one - can't quite remember what it was all about.
